### ISSUE TITLE
Firefly Lanterns causing crashes

### ISSUE THREAD

**Issue by ghost** [Turnip-Labs/bta-halplibe#13]
I noticed when using the newer versions for halplibe I have issues with hanging lanterns. Whenever I sleep in a bed with one above it or even just jump into one my game crashes. The issue is not present in version 2.1.1 which was the version I had before trying to upgrade to 2.2.0,  2.3.0 has the same issue. This is the report it gives me on the crash screen which hopefully may be of help.
--- BEGIN ERROR REPORT db2068b5 --------
Generated 2023-09-29, 12:17 a.m.

Minecraft: Better than Adventure! INDEV
OS: Windows 10 (amd64) version 10.0
Java: 18.0.1.1, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
LWJGL: 2.9.4-babric.1
OpenGL: NVIDIA GeForce RTX 3080/PCIe/SSE2 version 4.6.0 NVIDIA 536.99, NVIDIA Corporation

java.lang.NullPointerException: Cannot read field "id" because "item" is null
	at net.minecraft.core.item.ItemStack.<init>(ItemStack.java:67)
	at net.minecraft.core.block.BlockLanternFirefly.getBreakResult(BlockLanternFirefly.java:127)
	at toufoumaster.btwaila.gui.GuiBlockOverlay.updateBlockOverlayWindow(GuiBlockOverlay.java:326)
	at net.minecraft.client.gui.GuiIngame.handler$zzf000$renderGameOverlay(GuiIngame.java:1284)
	at net.minecraft.client.gui.GuiIngame.renderGameOverlay(GuiIngame.java:722)
	at net.minecraft.client.render.WorldRenderer.updateCameraAndRender(WorldRenderer.java:467)
	at net.minecraft.client.Minecraft.run(Minecraft.java:731)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MartinSVK12** [comment]
This is not a halplibe problem nor is it caused by it.
