### ISSUE TITLE
Another random crash, related to colors(?)

### ISSUE THREAD

**Issue by FatherCheese** [Turnip-Labs/bta-halplibe#29]
[11:12:26] [Client-Main] java.lang.RuntimeException: Failed to load colors from image: /misc/colors_flag.png
[11:12:26] [Client-Main] 	at net.minecraft.core.util.helper.Colors.fillColorArray(Colors.java:36)
[11:12:26] [Client-Main] 	at net.minecraft.core.util.helper.Colors.loadColors(Colors.java:25)
[11:12:26] [Client-Main] 	at net.minecraft.client.render.RenderEngine.refreshTextures(RenderEngine.java:609)
[11:12:26] [Client-Main] 	at net.minecraft.client.Minecraft.startGame(Minecraft.java:364)
[11:12:26] [Client-Main] 	at net.minecraft.client.Minecraft.run(Minecraft.java:2879)
[11:12:26] [Client-Main] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by FatherCheese** [comment]
Actually nvm, seems to be maybe a BTA issue?
